### PR TITLE
exchanges: add Swan Bitcoin

### PR DESCRIPTION
**Pull request by jstrnbrg**
- Adding Swan Bitcoin to the Buy & Sell page in the BitBoxApp. 
- Filters: North America & DCA 

Screenshot 2020-07-08 at 11 06 00

### CODE REVIEW

**Comment by jstrnbrg** [comment]
@thisconnect pls review

**Comment by jstrnbrg** [comment]
@x1ddos please set up a redirect for `https://ext.shiftcrypto.ch/swan_bitcoin` to `https://www.swanbitcoin.com/BitBox`. Thank you

**Comment by x1ddos** [comment]
> @x1ddos please set up a redirect for `https://ext.shiftcrypto.ch/swan_bitcoin` to `https://www.swanbitcoin.com/BitBox`. Thank you

Sent you a change on infrastructure repo.

**Comment by x1ddos** [comment]
Done:

$ curl -sI https://ext.shiftcrypto.ch/swan_bitcoin | grep Location:
Location: https://www.swanbitcoin.com/BitBox

**Comment by thisconnect** [comment]
@jstrnbrg 
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Commits must have valid signatures.
To github.com:digitalbitbox/bitbox-wallet-app.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:digitalbitbox/bitbox-wallet-app.git'
```

**Pull request merged**
