### PR TITLE
decrease minimum width for qt on desktop

### PR DESCRIPTION
**Pull request by jadzeidan**
This change decreases the minimum width of the BBApp window to 360px, which allows a user to see the mobile version of the UI on desktop if they wish.

### CODE REVIEW

**Comment by jadzeidan** [comment]
> What's with the `(#1)` in the commit title?
> 
> Also please prefix the commit title with `qt:`, see also [here](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/CONTRIBUTING.md#git-commits).

I'm not sure where the `(#1)` came from. Think it was autogenerated.

Ok I added prefix `qt:`

**Comment by benma** [comment]
> > What's with the `(#1)` in the commit title?
> > Also please prefix the commit title with `qt:`, see also [here](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/CONTRIBUTING.md#git-commits).
> 
> I'm not sure where the `(#1)` came from. Think it was autogenerated.
> 
> Ok I added prefix `qt:`

I don't see the prefix in the commit. Also simply remove the `(#1)`. Then force push the commit to your master branch (the one where you made this PR from) so the PR is updated.

**Comment by jadzeidan** [comment]
> > > What's with the `(#1)` in the commit title?
> > > Also please prefix the commit title with `qt:`, see also [here](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/CONTRIBUTING.md#git-commits).
> > 
> > 
> > I'm not sure where the `(#1)` came from. Think it was autogenerated.
> > Ok I added prefix `qt:`
> 
> I don't see the prefix in the commit. Also simply remove the `(#1)`. Then force push the commit to your master branch (the one where you made this PR from) so the PR is updated.

Sorry messed it up before. Is it correct now?

**Comment by x1ddos** [comment]
i see 3 commits. but this looks like a 3 characters change and should probably be a single commit:

image

**Comment by jadzeidan** [comment]
> i see 3 commits. but this looks like a 3 characters change and should probably be a single commit:
> 
> image

Created new PR with one commit: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1617

**Pull request closed without merging**
