### PR TITLE
Merge current master into staging-portfolio

### PR DESCRIPTION
**Pull request by x1ddos**
This is just so we have some recent commits from master in the staging-portfolio, too,  mainly to get the CI fixes into this branch.

### CODE REVIEW

**Review by benma — APPROVED** [review]
appveyor: `The remote server returned an error: (500) Internal Server Error.` :thinking:

**Comment by x1ddos** [comment]
> appveyor: `The remote server returned an error: (500) Internal Server Error.` thinking

what the hell. it was supposed to exit without pushing the artifact.

**Comment by x1ddos** [comment]
> > appveyor: `The remote server returned an error: (500) Internal Server Error.` thinking
> 
> what the hell. it was supposed to exit without pushing the artifact.


```
if defined APPVEYOR_PULL_REQUEST_NUMBER appveyor exit
mkdir %APPVEYOR_BUILD_FOLDER%
cp %GOPATH%\src\github.com\digitalbitbox\bitbox-wallet-app\frontends\qt\BitBox-installer.exe %APPVEYOR_BUILD_FOLDER%\BitBox-installer.exe
appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\BitBox-installer.exe
The remote server returned an error: (500) Internal Server Error.
```

**Comment by x1ddos** [comment]
> > appveyor: `The remote server returned an error: (500) Internal Server Error.` thinking
> 
> what the hell. it was supposed to exit without pushing the artifact.

ah, of course. this wasn't a pull request according to appveyor. this is: https://ci.appveyor.com/project/benma/bitbox-wallet-app/builds/35359109

```
Build started
git clone -q https://github.com/digitalbitbox/bitbox-wallet-app.git C:\projects\bitbox-wallet-app
git fetch -q origin +refs/pull/1010/merge
```

So, even though this is technically a PR for github. it isn't for appveyor I guess, maybe because all commits are from the same repo?

I'll merge as is and we'll find out.

**Comment by x1ddos** [comment]
What I expect to happen next is PRs should be all green now but when merged to master, appveyor will choke on artifact push again so merge commits will be red but hopefully for not too long.

**Pull request merged**
