### PR TITLE
Master to staging-revamp-settings

### PR DESCRIPTION
**Pull request by shonsirsha**

### CODE REVIEW

**Comment by shonsirsha** [comment]
@thisconnect not sure how you usually fix merge conflicts on (protected) staging branch - but I made a branch that fixed the merged conflicts of master into staging-revamp-settings (this PR). And I made a PR of merging that branch into this branch here: #2143 .

So if we merge #2143, we can merge this one too, then merge #2129. 😄 please lmk wyt.

**Comment by thisconnect** [comment]
yeah exactly, I am just not sure if I can review this. should i just approve your PR or can you point me to the places where there was a conflict. let me know if it makes sense to even review.

> For now I made a branch that fixed the merged conflicts of master into staging-revamp-settings (this PR). And I made a PR to merge that branch into this branch. PR is here: https://github.com/digitalbitbox/bitbox-wallet-app/pull/2143 .

**Comment by thisconnect** [comment]
merged! 

> EDIT: Probably makes sense to wait for https://github.com/digitalbitbox/bitbox-wallet-app/pull/2141 to get merged first actually :)

**Comment by shonsirsha** [comment]
> yeah exactly, I am just not sure if I can review this. should i just approve your PR or can you point me to the places where there was a conflict. let me know if it makes sense to even review.


Yes sounds good. The conflicts happened in `CHANGELOG`, `backend.ts` and `bitbox02.tsx`.
I think bitbox02 and backend will be most important. 

For `backend`, during the settings revamp development, I added (refactored) a new function and put one in there called `socksProxyCheck` [here](https://github.com/digitalbitbox/bitbox-wallet-app/blob/327c7bb5b44d129258ff9835385aa63d91622422/frontends/web/src/api/backend.ts). But youve reviewed this before, so more of a re-review (?) and it's just a small change anyway in this file.

For `bitbox02` would make sense to take a look again further. But looks good to me personally.

So once youve reviewed those, you can approve #2143 and I'll merge it. Then I can merge this one, and finally #2129 . 🤞 lmk wyt!

**Comment by shonsirsha** [comment]
#2143 merged! Feel free to approve this one too cc @thisconnect  🙏

**Review by thisconnect — APPROVED** [review]
untested LGTM

**Pull request merged**
