### PR TITLE
frontend: upgrade lightweight-charts to 4.x

### PR DESCRIPTION
**Pull request by thisconnect**
See https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4

### CODE REVIEW

**Comment by thisconnect** [comment]
Simplified a bit which fixed it, PTAL

**Comment by thisconnect** [comment]
rebased

**Comment by shonsirsha** [comment]
Just tested on webdev and seems to be working fine..

Anything in particular to test?

**Comment by thisconnect** [comment]
> Anything in particular to test?

I think it's good, I jus rebased and I'll try one more time.

**Pull request merged**
