### PR TITLE
Socksproxy

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by TheCharlatan** [comment]
Won't this make the app crash immediately if tor is not configured properly?

**Comment by benma** [comment]
Not unless I missed something. `GetTCPProxyDialer()` had one error path via `proxy.SOCKS5()`, and that function only returns `nil` for error:

**Comment by benma** [comment]
I do wonder why that function is like that. I highly dislike unused arguments/return values. Maybe it was more convenient for the stdlib to have a consistent signature for dialers? :man_shrugging:

**Comment by benma** [comment]
With all the passing of socksproxy/dialers/http clients to enable Tor, I am almost tempted to use an evil global singleton :scream: @x1ddos talk me out of it :joy:

**Comment by x1ddos** [comment]
Ok, I'll take a look at this whole socks business and report back here. :)

**Pull request merged**
