### PR TITLE
frontend: use CSS variables for account selector

### PR DESCRIPTION
**Pull request by shonsirsha**
We need to use proper CSS variables for the component so its styling will be appropriate for both dark and light mode.

Before:
Screenshot 2023-03-21 at 12 59 22

After:

Screenshot 2023-03-22 at 06 34 23
Screenshot 2023-03-22 at 06 34 30

### CODE REVIEW

**Comment by thisconnect** [comment]
please make the  background  of the select element white `#FFF` in lightmode so all input elements have same styling.

**Review by thisconnect — CHANGES_REQUESTED** [review]
please make the background of the select element white (`#FFF`) in light mode.

**Comment by shonsirsha** [comment]
> please make the background of the select element white (#FFF) in light mode.

Did you mean when it's selected? or when hovered? or both?

Actually come to think of it, this is how it looks like on master:

Screenshot 2023-03-21 at 18 56 50


🤔 do we want to have it like this?

**Comment by shonsirsha** [comment]
Changes made, screenshots updated.

**Comment by thisconnect** [comment]
> Did you mean when it's selected? or when hovered? or both?

neither, I meant in normal without focus nor active.

**Comment by thisconnect** [comment]
> this is how the selected and hovered state colour look like on master:
> do we want to have it like this too here?

selected and hover look good to me, but I might miss some context. I am about to open another PR first.

**Comment by thisconnect** [comment]
@shonsirsha I tested sean/frontend-account-selector-css-fix in lightmode 8f4b67d2bbc00c556ad7e70f1d77967ad5998d05 

I and prefer the full blue active as in master and  slightly prefer the lightblue hover too, but I dont have a strong opinion.

I guess the lightmode UI shouldn't change and just be as on master.

**Comment by shonsirsha** [comment]
> neither, I meant in normal without focus nor active.

Yup, understood :) 

> I guess the lightmode UI shouldn't change and just be as on master.

Yeah I agree. I'll make the change for the hover n selected colours so they look the same as seen on master.

**Comment by shonsirsha** [comment]
Changes made. PTAL :) @thisconnect 

I had to add new colours and variables in `variables.css` as they weren't available (the blue colours you see on master came from the library). 

I think this makes sense, as these new variables will also be used here: #2025, so we should merge this PR first before that one.

Updated screenshots:

Screenshot 2023-03-22 at 06 34 23
Screenshot 2023-03-22 at 06 34 30

**Pull request merged**
