### PR TITLE
frontend: type bitbox02 insert sdcard api 

### PR DESCRIPTION
**Pull request by thisconnect**
Ongoing effort to type all api calls, see:
- backend/devices/bitbox02/handlers/handlers.go

Looks like this was wrongly displaying errorMessage instead
of response.message.

on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1914

### CODE REVIEW

**Comment by thisconnect** [comment]
but I am not sure how to trigger an error or when this would fail.

**Comment by Beerosagos** [comment]
> but I am not sure how to trigger an error or when this would fail.

I think this can fail only with an error generated in the firmware and returned by the device query. The easiest way I see to test the error dialog is to generate a fake error and return it with `return maybeBB02Err(err, handlers.log), nil` in `postInsertSDCard`

**Review by Beerosagos — APPROVED** [review]
untested LGTM!

**Comment by thisconnect** [comment]
merged in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1940

**Pull request closed without merging**
