### PR TITLE
Staging darkmode -> master

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
Imo no need for this PR, we can merge staging to master instead: https://github.com/digitalbitbox/bitbox-wallet-app/pull/2028/

**Comment by benma** [comment]
> Imo no need for this PR, we can merge staging to master instead: #2028

I made this comment on the wrong PR. I meant we should keep this PR and close #2028. ACK?

**Comment by thisconnect** [comment]
> I made this comment on the wrong PR. I meant we should keep this PR and close https://github.com/digitalbitbox/bitbox-wallet-app/pull/2028. ACK?

ack, fyi I have one more PR incoming...
also we'll need to test that nothing changed on master.. but I did a quick codereview on the other master->darkmode PR and it looked good. but I migh thave missed something.

**Review by thisconnect — APPROVED** [review]
LGTM with comment.

**Pull request merged**
