### PR TITLE
nodejs: update node to latest lts version 18.16.0

### PR DESCRIPTION
**Pull request by thisconnect**
Tested on macOS:

- `make buildweb` (will update & install frontend/web/node_modules)
- `make webtest`
- `make webdev`
- `make weblint`

### CODE REVIEW

**Comment by thisconnect** [comment]
NPM shipped with Node.js 18.16.0 should be npm@9.5.1

you can also update `npm i -g npm@latest`, for which I got 9.6.6, both should work.

Note this changes the package-lock.json to v3, so we should all upgrade Node.js with this change.

**Comment by thisconnect** [comment]
I somehow have an issue with the  React devtools extension, "Loading React Element Tree... If this seems stuck, please follow the [troubleshooting instructions](https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#the-react-tab-shows-no-components)."

Screen Shot 2023-05-08 at 16 05 26

https://github.com/facebook/react/blob/main/packages/react-devtools/README.md#prerequisite-steps

Changing to older node i.e. v16.15.0 and restarting webdev seems to work.

Screen Shot 2023-05-08 at 16 00 18

**Comment by benma** [comment]
This needs a docker image update. @Beerosagos could you take care of it? Beware that https://github.com/digitalbitbox/bitbox-wallet-app/pull/2100/ also updates the Docker image, so the two PRs should be handled one after the other to avoid any silent conflicts.

**Comment by thisconnect** [comment]
@Beerosagos let me know if I should rebase on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/2100

**Comment by Beerosagos** [comment]
> @Beerosagos let me know if I should rebase on top of #2100

Would be great, thanks :pray:

**Comment by Beerosagos** [comment]
> > @Beerosagos let me know if I should rebase on top of #2100
> 
> ~Would be great, thanks pray~ EDIT: nevermind, I can rebase #2100 on this

Updating the docker image has been trickier than expected. I needed to upgrade our image base from ubuntu 18.04 to ubuntu 20.04 and fix a bunch of missing libs and small changes. I made a dedicated PR https://github.com/digitalbitbox/bitbox-wallet-app/pull/2110 and rebased #2100 on that.
In order to avoid silent conflicts (as @benma wisely suggested) pls rebase this on top of #2100 :pray: 

Thanks!

**Comment by thisconnect** [comment]
rebased on PR #2100 (Beerosagos:android-studio-fix

> In order to avoid silent conflicts (as @benma wisely suggested) pls rebase this on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/2100 🙏

**Review by Beerosagos — APPROVED** [review]
tACK for the update nodejs commits, let's wait for the reviews on #2100 and #2110

**Comment by Beerosagos** [comment]
> tACK for the update nodejs commits, let's wait for the reviews on #2100 and #2110

Both PR got merged

**Comment by thisconnect** [comment]
@Beerosagos somehow macOS ci still sais node 14.x 

see https://github.com/digitalbitbox/bitbox-wallet-app/actions/runs/5054361597/jobs/9069203428#step:5:3295

**Comment by Beerosagos** [comment]
> @Beerosagos somehow macOS ci still sais node 14.x
> 
> see https://github.com/digitalbitbox/bitbox-wallet-app/actions/runs/5054361597/jobs/9069203428#step:5:3295

The CI you linked is from PR #2100 right? Then I guess it is correct. CI for this PR says v18 (see https://github.com/digitalbitbox/bitbox-wallet-app/actions/runs/4949145633/jobs/8850857269?pr=2091#step:5:2343). Does it sounds right?

**Comment by thisconnect** [comment]
aaah, that makes sense.

> The CI you linked is from PR https://github.com/digitalbitbox/bitbox-wallet-app/pull/2100 right?

**Pull request merged**
