### PR TITLE
staging-portfolio: pull latest from master

### PR DESCRIPTION
**Pull request by x1ddos**
This is to keep them close and make it easier to merge
staging-portfolio into master when we're ready.

Also, should make macOS github CI work again: master has a commit that
fixes a homebrew cleanup issue.

### CODE REVIEW

**Review by benma — APPROVED** [review]
Hmm when I rebase I don't get any merge commits.

**Comment by x1ddos** [comment]
> Hmm when I rebase I don't get any merge commits.

But there are many: 7c2b980, 3321dcb, eeff139 and so on.

**Comment by benma** [comment]
> > Hmm when I rebase I don't get any merge commits.
> 
> But there are many: [7c2b980](https://github.com/digitalbitbox/bitbox-wallet-app/commit/7c2b9804c204d0b4a5972fad80575be2c5c949a1), [3321dcb](https://github.com/digitalbitbox/bitbox-wallet-app/commit/3321dcb7ddc0cd55687469ac6bdc58219a588ea6), [eeff139](https://github.com/digitalbitbox/bitbox-wallet-app/commit/eeff1391b11b658e07bfb5a843b821c15cb79892) and so on.

Yeah just when I do a rebase, git is somehow smart enough to skip over all the merge commits. 

The as when I made PRs to merge staging into master, like https://github.com/digitalbitbox/bitbox-wallet-app/pull/987/commits. No merge commits in the PR, even though there were of course plenty of them in the staging branch.

**Comment by x1ddos** [comment]
> > > Hmm when I rebase I don't get any merge commits.
> > 
> > 
> > But there are many: [7c2b980](https://github.com/digitalbitbox/bitbox-wallet-app/commit/7c2b9804c204d0b4a5972fad80575be2c5c949a1), [3321dcb](https://github.com/digitalbitbox/bitbox-wallet-app/commit/3321dcb7ddc0cd55687469ac6bdc58219a588ea6), [eeff139](https://github.com/digitalbitbox/bitbox-wallet-app/commit/eeff1391b11b658e07bfb5a843b821c15cb79892) and so on.
> 
> Yeah just when I do a rebase, git is somehow smart enough to skip over all the merge commits.
> 
> The same as when I made PRs to merge staging into master, like https://github.com/digitalbitbox/bitbox-wallet-app/pull/987/commits. No merge commits in the PR, even though there were of course plenty of them in the staging branch.

Ah, rebase. Sure, that would be different but if I rebase you and @thisconnect will have a broken copy of staging-portfolio branch. Unless you know a way to push a rebase without `-f`.

**Comment by benma** [comment]
The rebase would be the other way: master on top of staging. But anyway, I guess it does not matter much. Let's hope the merge commits will disappear again when finally making a PR to master.

**Comment by x1ddos** [comment]
> The rebase would be the other way: master on top of staging. But anyway, I guess it does not matter much. Let's hope the merge commits will disappear again when finally making a PR to master.

rebase master on top of staging... what do you mean? if you rebase master, all local copies will be invalidated. unless again you have a way of doing it without `-f` git force push.

**Comment by x1ddos** [comment]
> Let's hope the merge commits will disappear 

if you really want to get rid of merge commits, it starts with using cherry-picks or fast-forward merges only :)

**Comment by benma** [comment]
>  it starts with using cherry-picks

Rebasing master on top of staging is the same as cherry picking the master commits to staging... 

Anyway, let's merge this :D

**Comment by x1ddos** [comment]
> > it starts with using cherry-picks
> 
> Rebasing master on top of staging is the same as cherry picking the master commits to staging...
> 
> Anyway, let's merge this :D

The end result, when staging-portfolio is merged with master, would be different. In the rebase case, all original master commit hashes are gone and IIRC would also invalidate assertion.txt for v4.23.0. When cherry picking, commits in master stay the same.

**Comment by benma** [comment]
> The end result, when staging-portfolio is merged with master, would be different. In the rebase case, all original master commit hashes are gone

Wouldn't they be gone only in the staging branch, but when merging to master, the original commits win? 

>  IIRC would also invalidate assertion.txt for v4.23.0

Wrong repo :P

**Comment by x1ddos** [comment]
> > The end result, when staging-portfolio is merged with master, would be different. In the rebase case, all original master commit hashes are gone
> 
> Wouldn't they be gone only in the staging branch, but when merging to master, the original commits win?

If you're rebasing master, you're literally changing commit history in the master branch so there wouldn't be any original commits left. I mean master-original commits. Plus, github wouldn't even let you push a rebased master without `-f`.

> > IIRC would also invalidate assertion.txt for v4.23.0
> 
> Wrong repo :P

:see_no_evil: very much so :laughing:

**Comment by benma** [comment]
> If you're rebasing master, you're literally changing commit history in the master branch so there wouldn't be any original commits left. I mean master-original commits. Plus, github wouldn't even let you push a rebased master without `-f`.
> 
> > >

I think you misunderstand me completely lol. I am not saying to push a rebased master to upstream master at all...

**Comment by x1ddos** [comment]
> > If you're rebasing master, you're literally changing commit history in the master branch so there wouldn't be any original commits left. I mean master-original commits. Plus, github wouldn't even let you push a rebased master without `-f`.
> > > >
> 
> I think you misunderstand me completely lol. I am not saying to push a rebased master to upstream master at all...

Yeah, I'm convinced I misunderstand because for sure you know better than rebasing master :) but that's what you said:

> Rebasing master on top of staging

I just don't see how to send a pull request of staging-portfolio + master merge while keeping master intact and preserving the original commits in staging-portfolio branch. Cherry-picking? Yes but that's what I was saying. You meant something else, I think.

**Pull request merged**
