### PR TITLE
frontend: support deactivating account

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/1336

**Review by thisconnect — APPROVED** [review]
LGTM

**Comment by thisconnect** [comment]
@benma I just found out why half of my accounts aren't showing anymore :) , please rebase and merge, let me know if I should.

**Comment by benma** [comment]
> @benma I just found out why half of my accounts aren't showing anymore :) , please rebase and merge, let me know if I should.

Done ;)

**Pull request merged**
