### PR TITLE
frontend: add Arabic translation

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Review by thisconnect — APPROVED** [review]
LGTM 👍

**Comment by thisconnect** [comment]
Note: this still uses LTR (left-to-right) next step would be to add full RTL support and flip everything, but can be done later.

**Comment by thisconnect** [comment]
@jadzeidan PTAL

**Comment by jadzeidan** [comment]
Noticed one bug:

image

I will make a fix on locize.

**Review by thisconnect — CHANGES_REQUESTED** [review]
Oups I was too early with approving. There seems to be an issue with `manageAccounts.addAccount`, we'll update locize, please wait with merging

**Comment by jadzeidan** [comment]
@benma I updated locize with the fix. Please pull again.

**Comment by benma** [comment]
> @benma I updated locize with the fix. Please pull again.

It was incorrect again - let's just remove the key by merging this first: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1844

**Comment by jadzeidan** [comment]
> It was incorrect again - let's just remove the key by merging this first: #1844

Locize seems to be flipping it automatically.

image

But if removing it works, that's great 👍

**Comment by benma** [comment]
Removed the key and pulled locize again, PTAL

**Review by thisconnect — APPROVED** [review]
PR LGTM

with question: did you delete `manageAccounts.addAccount` key in locize?

**Comment by benma** [comment]
> PR LGTM
> 
> with question: did you delete `manageAccounts.addAccount` key in locize?

No, deleted in en/app.json, then did locize-push.

**Pull request merged**
