### PR TITLE
frontend: styling for fee targets and custom fee on small screen

### PR DESCRIPTION
**Pull request by thisconnect**
With expert custom fee enabled the feetargets use now more space
as it displays sats per byte information. This change breaks the
proposed fee text onto a new line, but keeps the custom fee on
the same line on small screen.

Screen Shot 2020-09-03 at 3 42 36 PM 
Screen Shot 2020-09-03 at 3 42 46 PM

### CODE REVIEW

**Comment by x1ddos** [comment]
All looks great on small screens but desktop has the right side of the fee dropdown cut off:

image

Feels a bit weird, unfinished.

**Review by x1ddos — APPROVED** [review]
Actualy, I've realized this PR is about small things which looks great. @thisconnect tells me there's a separate issue about styling on larger screens, so LGTM.

**Comment by x1ddos** [comment]
BTW ci/macos failing is unrelated. I sent https://github.com/digitalbitbox/bitbox-wallet-app/pull/990 to make it great again.

**Comment by thisconnect** [comment]
> Actualy, I've realized this PR is about small screens which looks great. @thisconnect tells me there's a separate issue about styling on larger screens, so LGTM.

I'll merge this and open a new PR for medium/large screens

**Pull request merged**
