### PR TITLE
golang: update to 1.14.4

### PR DESCRIPTION
**Pull request by benma**
shiftcrypto/bitbox-wallet-app:5 created and based on the change in the
Docker image.

### CODE REVIEW

**Comment by x1ddos** [comment]
With go1.14 now, how about removing `GO111MODULE=off` and lifting the requirement of 

> Clone this repository to $GOPATH/src/github.com/digitalbitbox/bitbox-wallet-app ...

in https://github.com/digitalbitbox/bitbox-wallet-app#requirements?

I've just tried building frontend/android/goserver with gomobile on 1.14 without GO111MODULE=off and it seems to work:

```
$ gomobile bind -x -a -ldflags="-s -w" -target android .
WORK=/tmp/gomobile-work-303315762
GOOS=android CGO_ENABLED=1 $GOPATH/bin/gobind -lang=go,java -outdir=$WORK github.com/digitalbitbox/bitbox-wallet-app/frontends/android/goserver
mkdir -p $WORK/src
...
$ ls -lh
total 37M
415 Nov  9  2019 Makefile
135 Nov  9  2019 README.md
8.0K Jun  7 10:02 goserver-sources.jar
37M Jun  7 10:02 goserver.aar
5.2K May 14 19:10 goserver.go
```

This repo is the only one living in my old GOPATH.

**Comment by x1ddos** [comment]
> With go1.14 now, how about removing `GO111MODULE=off` and lifting the requirement of

We'll have to do it sooner or later. Why not now.

**Comment by benma** [comment]
> With go1.14 now, how about removing `GO111MODULE=off` and lifting the requirement of
> 
> > Clone this repository to $GOPATH/src/github.com/digitalbitbox/bitbox-wallet-app ...
> 
> in https://github.com/digitalbitbox/bitbox-wallet-app#requirements?
> 
> I've just tried building frontend/android/goserver with gomobile on 1.14 without GO111MODULE=off and it seems to work:
> 
> ```
> $ gomobile bind -x -a -ldflags="-s -w" -target android .
> WORK=/tmp/gomobile-work-303315762
> GOOS=android CGO_ENABLED=1 $GOPATH/bin/gobind -lang=go,java -outdir=$WORK github.com/digitalbitbox/bitbox-wallet-app/frontends/android/goserver
> mkdir -p $WORK/src
> ...
> $ ls -lh
> total 37M
> 415 Nov  9  2019 Makefile
> 135 Nov  9  2019 README.md
> 8.0K Jun  7 10:02 goserver-sources.jar
> 37M Jun  7 10:02 goserver.aar
> 5.2K May 14 19:10 goserver.go
> ```
> 
> This repo is the only one living in my old GOPATH.

With go1.14 now, how about removing `GO111MODULE=off` and lifting the requirement of 

> Clone this repository to $GOPATH/src/github.com/digitalbitbox/bitbox-wallet-app ...

in https://github.com/digitalbitbox/bitbox-wallet-app#requirements?

I've just tried building frontend/android/goserver with gomobile on 1.14 without GO111MODULE=off and it seems to work:

```
$ gomobile bind -x -a -ldflags="-s -w" -target android .
WORK=/tmp/gomobile-work-303315762
GOOS=android CGO_ENABLED=1 $GOPATH/bin/gobind -lang=go,java -outdir=$WORK github.com/digitalbitbox/bitbox-wallet-app/frontends/android/goserver
mkdir -p $WORK/src
...
$ ls -lh
total 37M
415 Nov  9  2019 Makefile
135 Nov  9  2019 README.md
8.0K Jun  7 10:02 goserver-sources.jar
37M Jun  7 10:02 goserver.aar
5.2K May 14 19:10 goserver.go
```

This repo is the only one living in my old GOPATH.

_Originally posted by @x1ddos in https://github.com/digitalbitbox/bitbox-wallet-app/pull/850#issuecomment-640175185_

README updated.

Without `GO111MODULE=off`, I believe you are building the mobile bindings without the vendored deps. There is no `-mod=vendor` flag in `gomobile bind` (yet or ever?).

**Comment by x1ddos** [comment]
> Without `GO111MODULE=off`, I believe you are building the mobile bindings without the vendored deps. There is no `-mod=vendor` flag in `gomobile bind` (yet or ever?).

Oh, you're right! Didn't realize in my previous build in https://github.com/digitalbitbox/bitbox-wallet-app/pull/850#issuecomment-640175185 it was actually downloading packages, revealed by adding `-v` verbose flag.

Commented on https://github.com/golang/go/issues/34181.

**Comment by x1ddos** [comment]
A couple other places to update to 1.14:

- https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/go.mod#L3
- https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35
- https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35

**Comment by benma** [comment]
> A couple other places to update to 1.14:
> 
>     * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/go.mod#L3
> 
>     * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35
> 
>     * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35

done (the last two are the same)

**Comment by x1ddos** [comment]
> > A couple other places to update to 1.14:
> > ```
> > * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/go.mod#L3
> > 
> > * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35
> > 
> > * https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L35
> > ```
> 
> done (the last two are the same)

sorry, last one was copy&paste error. it was supposed to be https://github.com/digitalbitbox/bitbox-wallet-app/blob/04925927/Makefile#L39, in `osx-init` make target. looks like it's still at 1.13.

**Comment by benma** [comment]
> make target. looks like it's still at 1.13.

ah maybe that's why it didn't work.

anyway, lots of places to update the Go version in :O

**Comment by benma** [comment]
> Somehow `vendor/modules.txt` updates got into the `update to 1.14` commit but ok.

hmm i did `make go-vendor` in an interactive rebase in every commit.

**Pull request merged**
