### PR TITLE
frontend: fix resizing chart

### PR DESCRIPTION
**Pull request by thisconnect**
Sometimes the chart did not resize properly, leaving half of the
area empty.

Removed setTimeout hack and just call chart.timeScale().fitContent()
seem to fix this.

### CODE REVIEW

**Comment by thisconnect** [comment]
Please also test on linux cc @strmci

**Comment by strmci** [comment]
tested with qt-linux, looks good

**Comment by thisconnect** [comment]
> On macOS qt: seems like when resizing from a small screen to a bigger one the chart overflows.

nice catch. Looks like it happens when there is a single resize event that changes the window and sidebar visiblity.

rebased..

**Comment by thisconnect** [comment]
> On macOS qt: seems like when resizing from a small screen to a bigger one the chart overflows.

Should be fixed now, if there was only a single resize event when clicking on maximize window the isMobile wasn't properly take into account.

**Pull request merged**
