### PR TITLE
frontend/i18n: fix backups

### PR DESCRIPTION
**Pull request by benma**
Needs to take `t` from props, otherwise the labels won't be updated when the language is changed.

### CODE REVIEW

**Comment by KasparEtter** [comment]
I know I'm too late but generally I'd prefer that we use functional components whenever possible (i.e. when no state is required).

**Comment by benma** [comment]
Not sure how it applies. This component has no state?

**Comment by KasparEtter** [comment]
You turned a function into a class for no good reason – other than not knowing how to apply a decorator to a function.

**Comment by benma** [comment]
I think the bigger issue was that I did not see that a function is better than a class. Will learn more from you soon on the topic!

**Pull request merged**
