### PR TITLE
Renew app icon

### PR DESCRIPTION
**Pull request by validblock**
Updating app icon according to the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon).

### CODE REVIEW

**Comment by thisconnect** [comment]
Thanks @validblock , there is also `trayicon.png` (the one shown in the macos menu) and `icon.icns` (afaik used for the actual app icon) that should be updated at the same time.

Would you mind share the source file?

**Comment by validblock** [comment]
> trayicon.png (the one shown in the macos menu)

Do we really need the menu? The menu does one little thing: Quit the app. Just saying ;)

> icon.icns

I saw, the `icns` file will be generated by using [convert_icon.sh](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/resources/MacOS/convert_icon.sh) from the updated `app_icon_source.png` file.

Attached all resources used by me.
[Archive.zip](https://github.com/digitalbitbox/bitbox-wallet-app/files/8111906/Archive.zip)

**Comment by benma** [comment]
> Do we really need the menu? The menu does one little thing: Quit the app. Just saying ;)

The menu is actually needed to enable desktop notifications, as strange as that sounds. It's a Qt restriction.

**Comment by thisconnect** [comment]
@validblock thanks for the resources.

ACK from my side to the new macOS desktop icon, but I guess the Android icon should stay as is.

**Comment by validblock** [comment]
> ACK from my side to the new macOS desktop icon, but I guess the Android icon should stay as is.

I would create a single icon for each OS. No convert scripts from a master icon anymore.

**Comment by validblock** [comment]
I try to generate an Android app icon by using the [Android Asset Studio](https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html). The result is the same icon set as [already exists](https://github.com/digitalbitbox/bitbox-wallet-app/tree/master/frontends/android/BitBoxApp/app/src/main/res). No difference. Stay this way.

ic_launcher

**Comment by validblock** [comment]
Regarding to the article [Create a macOS Menu Bar Application](https://medium.com/@acwrightdesign/creating-a-macos-menu-bar-application-using-swiftui-54572a5d5f87) I would suggest the following tray icon:

trayicon
_White Shift Crypto logo on a transparent background with spacing/padding around_

Ok? Then I will update the pull request by replacing the [trayicon.png](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/resources/trayicon.png).

**Comment by thisconnect** [comment]
> Ok? Then I will update the pull request by replacing the [trayicon.png](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/resources/trayicon.png).

I think it makes sense to update the trayicon.

> I saw, the icns file will be generated by using [convert_icon.sh](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/resources/MacOS/convert_icon.sh) from the updated app_icon_source.png file.

Could you also run `convert_icon.sh` and update https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/resources/MacOS/Testnet.app/Contents/Resources/icon.icns ?

also I wanted todo before but forgot: cc @jadzeidan PTAL

**Comment by jadzeidan** [comment]
Ack. Change makes sense. LGTM :)

**Comment by thisconnect** [comment]
@validblock do you have time to  commit the generated icons too so we could just merge this?

**Comment by thisconnect** [comment]
LGTM

Screen Shot 2022-03-03 at 8 52 21 AM

Screen Shot 2022-03-03 at 8 52 57 AM

Screen Shot 2022-03-03 at 8 53 19 AM

Screen Shot 2022-03-03 at 8 54 18 AM

**Comment by thisconnect** [comment]
@benma could you test Android?

**Comment by benma** [comment]
@thisconnect is the icon supposed to change on all platforms? If so, the icons on Android, Windows and Linux have to be compiled as well.

- frontends/qt/resources/win/convert.sh
- frontends/android/mkicon.sh
- frontends/qt/resources - `make`

I ran these and this is the output for me: https://github.com/benma/bitbox-wallet-app/commit/0bac53f4f17ddccb154e2ae88bcc6b12ada99ded 

After this, on Android it looks like this (DEBUG is new, BitBoxApp is old)

image

On linux:

Before:

image

After:

image

Is this good?

**Comment by thisconnect** [comment]
macOS and linux LGTM.

I don't like that the logo is so big  on Android.

CC @jadzeidan WDYT?

**Comment by jadzeidan** [comment]
I'm not sure how the Android icon is generated. I the background autogenerated and you just need to provide the correct size logo in the middle?

**Comment by jadzeidan** [comment]
> @jadzeidan see my comment above
> 
> https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/android/mkicon.sh

So what's the best fix to make the logo on Android smaller. Provide a smaller logo specifically for Android?

**Comment by benma** [comment]
In the info screen it looks good however:

image


Seems my launcher somehow cuts off the icon a bit.

**Comment by benma** [comment]
There is also a "round icon", what a nightmare :joy: 

https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml#L18

**Comment by thisconnect** [comment]
> So what's the best fix to make the logo on Android smaller. Provide a smaller logo specifically for Android?

I'd assume it looks better if there is a bit more whitespace for the android?

Alternative: keep as is or change the old one to have a white BG ?

**Comment by thisconnect** [comment]
@jadzeidan could you make a different icon for android that has 20% white space on each side? so the actual logo  takes up about 60% of the image?

**Comment by jadzeidan** [comment]
@thisconnect 

Does this work?

shiftcrypto-logo-2

**Comment by jadzeidan** [comment]
@thisconnect here is PNG version:

shiftcrypto-logo-2

**Comment by validblock** [comment]
Any blocker there?

**Comment by benma** [comment]
@validblock sorry the blocker here was me, I was absent for two weeks and need to test the above Android logo. Will do so in the coming days. Sorry that this PR is taking so long :exploding_head:

**Comment by benma** [comment]
Sorry for the very long delay!

@jadzeidan the icon you provided looks good to me:

image


(BitBoxApp DEBUG is new, BitBoxApp is old).

Too bad it is not documented anywhere how the round icons were generated :/

@validblock i took the liberty of adding a commit to this PR with the change for Android.

@thisconnect anything else missing or is this good to squash and merge?

**Comment by benma** [comment]
Thanks very much @validblock and sorry again that this took so long!

**Pull request merged**
