### PR TITLE
frontend: fix exchange selection color in lightmode

### PR DESCRIPTION
**Pull request by thisconnect**
Background should be white and border lightgray, was using wrong CSS variables.

### CODE REVIEW

**Comment by thisconnect** [comment]
current/wrong:

image

new/corrected (with this PR):

Screen Shot 2023-04-06 at 11 50 16

**Comment by thisconnect** [comment]
this changes also darkmode to, which I think looks acceptable:

Screen Shot 2023-04-06 at 11 50 05

**Comment by jadzeidan** [comment]
Nice, LGTM

**Review by shonsirsha — APPROVED** [review]
good catch, LGTM!

**Pull request merged**
