### PR TITLE
Staging i18next > master

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by thisconnect** [comment]
@benma we have to rename some they keys in locize

**Comment by benma** [comment]
> @benma we have to rename some they keys in locize

i don't know how this works. if we locize-push after this PR, maybe locize will delete the previous keys (and all translations) and add the new ones, untranslated, which would be losing translations. need to look at docs to learn how to rename a key for all languages.

**Comment by x1ddos** [comment]
> if we locize-push after this PR, maybe locize will delete the previous keys (and all translations)

it is possible to make a locize backup first? assuming one can restore from it later.

**Comment by thisconnect** [comment]
i think we can pull, checkout the commit and then push, let's discuss offline.

**Review by benma — APPROVED** [review]
utACK

**Pull request merged**
