### PR TITLE
frontend: update dev dependencies

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by thisconnect** [comment]
Updated dev dependencies see also https://github.com/digitalbitbox/bitbox-wallet-app#npm-dependencies

```
cd frontends/web
rm package-lock.json
rm -rf node_modules
npm i --ignore-scripts
```

With this you should get the same package-lock.json unless something got updated in the meantime. 

It could well be that webdev doesn't work correctly with ` --ignore-scripts` as iirc esbuild tries to download a different binary on Linux, but it can't due to ` --ignore-scripts`.

So `--ignore-scripts` is only useful to create the lock file, but to have normally working webdev, you'll have to do `npm install` without ignore scripts.

Successfully tested the following on macOS:

```
make qt-osx
make webdev
make weblint
make webtest
```

**Comment by thisconnect** [comment]
rebased

**Comment by NicolaLS** [comment]
```bash
git fetch upstream pull/2298/head:frontend-update-deps
git checkout frontend-update-deps
nvm use --lts
cd frontends/web/
rm package-lock.json
rm -rf node_modules
npm i --ignore-scripts
```

gives me a [diff](https://gist.github.com/NicolaLS/d1c21d1d613910a891134c8670574144) but I guess this is not avoidable if the PR is not merged immediately @thisconnect ?

**Comment by thisconnect** [comment]
updated the PR, seems deps updated related to testing and lint-ing. yeah unavoidable, as soon as we have a lock file some deps will always update.. but we can regularly update the lock.


```
% npm list define-data-property
bitboxapp@0.0.0 ~/app/frontends/web
└─┬ eslint-config-react-app@7.0.1
  ├─┬ eslint-plugin-import@2.28.1
  │ └─┬ array-includes@3.1.7
  │   └─┬ define-properties@1.2.1
  │     └── define-data-property@1.1.1
  └─┬ eslint-plugin-react@7.33.2
    └─┬ string.prototype.matchall@4.0.10
      └─┬ set-function-name@2.0.1
        └── define-data-property@1.1.1 deduped

connect@computer web % npm list electron-to-chromium
bitboxapp@0.0.0 ~/app/frontends/web
└─┬ @babel/plugin-proposal-private-property-in-object@7.21.11
  └─┬ @babel/core@7.23.2
    └─┬ @babel/helper-compilation-targets@7.22.15
      └─┬ browserslist@4.22.1
        └── electron-to-chromium@1.4.554

connect@computer web % npm list function-bind       
bitboxapp@0.0.0 ~/app/frontends/web
├─┬ @testing-library/jest-dom@6.1.4
│ └─┬ aria-query@5.1.3
│   └─┬ deep-equal@2.2.2
│     ├─┬ call-bind@1.0.2
│     │ └── function-bind@1.1.2 deduped
│     └─┬ get-intrinsic@1.2.1
│       └── function-bind@1.1.2 deduped
└─┬ eslint-config-react-app@7.0.1
  └─┬ eslint-plugin-react@7.33.2
    └─┬ es-iterator-helpers@1.0.15
      └── function-bind@1.1.2

connect@computer web % npm list loupe        
bitboxapp@0.0.0 ~/app/frontends/web
└─┬ vitest@0.34.6
  ├─┬ @vitest/utils@0.34.6
  │ └── loupe@2.3.7
  └─┬ chai@4.3.10
    └── loupe@2.3.7 deduped

connect@computer web % npm list magic-string
bitboxapp@0.0.0 ~/app/frontends/web
└─┬ vitest@0.34.6
  ├─┬ @vitest/snapshot@0.34.6
  │ └── magic-string@0.30.5 deduped
  └── magic-string@0.30.5
```

**Pull request merged**
