### PR TITLE
frontend: make locize-pull

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by thisconnect** [comment]
@benma not sure why but this is missing: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1461/files#diff-6631e5e7b36d6349336cdf14e4f91eeeb8f284d449b8281af375936bbe94ae79R1045

Screen Shot 2021-11-10 at 3 24 47 PM

**Comment by thisconnect** [comment]
> not sure why but this is missing

I'll have to update the text again.

**Comment by thisconnect** [comment]
@benma please pull again

**Comment by benma** [comment]
@thisconnect done, PTAL

**Review by thisconnect — APPROVED** [review]
LGTM

**Pull request merged**
