### PR TITLE
frontend: make locize-pull

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by thisconnect** [comment]
I see, this will have to come later as the necessary change in the frontend hasn't been merged. If there is anything else that needs to be pulled from locize I'll revert that change in Locize.

**Comment by benma** [comment]
> I see, this will have to come later as the necessary change in the frontend hasn't been merged. If there is anything else that needs to be pulled from locize I'll revert that change in Locize.

You changed on locize before it was on master? :scream: :joy: 

This is the only change in locize for now, so it's ok for now.

**Comment by thisconnect** [comment]
Yeah I assumed we could merge my changes by now. I will revert it in Locize.

> You changed on locize before it was on master? 😱 😂

**Comment by thisconnect** [comment]
superseded by https://github.com/digitalbitbox/bitbox-wallet-app/pull/1552

**Pull request closed without merging**
