### PR TITLE
frontend: convert i18n to typescript

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by thisconnect** [comment]
I was hoping this would fail because an old import doesn't exist anymore:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/72eff2d98e2a70e2de5c5efbe2d15dd759f3fbab/frontends/web/src/app.tsx#L35

**Comment by thisconnect** [comment]
I'll squash all commits to 1 once reviewed.

**Review by shonsirsha — APPROVED** [review]
tested LGTM. Thanks for the initiative!

**Comment by shonsirsha** [comment]
commit msg looks good 👍 :)

**Pull request merged**
