### PR TITLE
backend: check account support by keystore also when loading

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by benma** [comment]
Builds on #1322

**Comment by x1ddos** [comment]
> Edtion switch

Did you mean Edition? and by edition, did you mean... Rust edition?

**Comment by benma** [comment]
> > Edtion switch
> 
> Did you mean Edition? and by edition, did you mean... Rust edition?



> > Edtion switch
> 
> Did you mean Edition? and by edition, did you mean... Rust edition?

Renamed the title.. Sorry sometimes I just keep the default name which is based off my branch name...

**Review by x1ddos — APPROVED** [review]
Oh, very good find :+1: 

On a related note, I wonder what happens in reverse. A btc-only restored on the regular. Since the initial default accounts were stored while using btc-only, so only BTC, will the user be able to see and add other coin accounts, i.e. ETH?

**Comment by x1ddos** [comment]
> will the user be able to see and add other coin accounts, i.e. ETH?

I mean I know they should be. Just checking if there are any potential bugs.

**Comment by benma** [comment]
> I mean I know they should be. Just checking if there are any potential bugs.

Yes it works - one can add the altcoins, but they won't be added by default - that only happens if there are no persisted accounts at all yet.

**Pull request merged**
