### PR TITLE
qt/windows: hide CMD window when queriyng for darkmode

### PR DESCRIPTION
**Pull request by benma**
When starting the app and when toggling darkmode, a CMD window would pop up on Windows very quickly during the execution of `reg query ...`.

### CODE REVIEW

**Review by Beerosagos — APPROVED** [review]
utACK

**Comment by benma** [comment]
@Beerosagos fixed, ptal again!

**Comment by Beerosagos** [comment]
> @Beerosagos fixed, ptal again!

Nice! LGTM

**Comment by Beerosagos** [comment]
> > @Beerosagos fixed, ptal again!
> 
> Nice! LGTM

Also tested on Linux/Cinnamon :+1:

**Comment by benma** [comment]
I tested Win/macOS :+1:

**Pull request merged**
