### PR TITLE
add non-standard library path to postinst script

### PR DESCRIPTION
**Pull request by jvaltin**
Add the BitBox library path to the system library path.

### CODE REVIEW

**Comment by benma** [comment]
Why? The libs are being loaded from there already, aren't they?

**Comment by jvaltin** [comment]
Without those two entries, libserver.so and libQT5Web*.so are not located at run time on my test systems.

**Comment by benma** [comment]
Why not? Did it work with the build scripts currently on master? The app is supposed to find all libs locally, without changing the ld search path.

**Comment by jvaltin** [comment]
> Why not? Did it work with the build scripts currently on master? The app is supposed to find all libs locally, without changing the ld search path.

The debs from the last release work on my system. The debs I produced from the repo did not work on my system. Adding this to my build process allowed BitBox to run.

**Comment by benma** [comment]
When I asked why, I asked for why it works everywhere but not on your system. The commit should fix the root of the issue, ideally without changing the host system, and if not possible, the commit message should have an adequate explanation for how your system is different than the rest.

Also feel free to close if it is low prio.

**Comment by benma** [comment]
Closing due to inactivity. Please reopen if this is a priority.

**Pull request closed without merging**
