### PR TITLE
Update release versions

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by x1ddos** [comment]
This should hold off until after #894, #895 and #896 are merged, right.

**Comment by benma** [comment]
> This should hold off until after #894, #895 and #896 are merged, right.

not at all, it can be merged at any time. this is merely a PR, not a release tag ;)

**Comment by benma** [comment]
rebased :D

**Comment by x1ddos** [comment]
> rebased :D

:heart:

**Pull request merged**
