### PR TITLE
frontend: add indentation eslint rule

### PR DESCRIPTION
**Pull request by thisconnect**
Some code has inconsistent indentation, sometimes  1 space,
currently the project uses 4 spaces.

See also https://eslint.org/docs/rules/indent

This commit is not complete and will not lint yet.

### CODE REVIEW

**Comment by thisconnect** [comment]
@BrianCraig @benma @x1ddos WDYT?

Should we do it now?

Actually I would prefer to change to 2 spaces, any opinion?

I know @benma (strongly?) prefers Crockford switch/case (no indentation), I slightly find it more readable to indent switch case, but can live with no indentation for case. Opinion?

**Comment by BrianCraig** [comment]
> @BrianCraig @benma @x1ddos WDYT?
> 
> Should we do it now?
> 
> Actually I would prefer to change to 2 spaces, any opinion?
> 
> I know @benma (strongly?) prefers Crockford switch/case (no indentation), I slightly find it more readable to indent switch case, but can live with no indentation for case. Opinion?

I also prefer 2 spaces over 4, and i don't have any preference over switch cases,

**Comment by x1ddos** [comment]
i've always seen switch case indented in javascript and i'm used to that.
don't really care about 4 vs 2 spaces but jsx code never fit on my screen due to long lines so maybe 2 spaces would actually make it better :+1:

**Comment by thisconnect** [comment]
I checked with @benma he is ok with indented switch case and 2 spaces.

**Comment by thisconnect** [comment]
since there are no open PR to `staging-react` it might be a good time to change that now...

another one would be to force semicolon.

@BrianCraig wdyt, should we do it now?

**Comment by thisconnect** [comment]
closing in favor of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1591

**Pull request closed without merging**
