### PR TITLE
Qt5.12.8

### PR DESCRIPTION
**Pull request by benma**
This takes the relevant parts of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1139 to move to ghcr for CI.

### CODE REVIEW

**Comment by benma** [comment]
Now running into this for Android: https://github.com/golang/go/issues/42655

**Comment by x1ddos** [comment]
> Now running into this for Android: [golang/go#42655](https://github.com/golang/go/issues/42655), same as in #1139 .. strange, since the android sdk and golang version didn't change in the Dockerfile

Yeah, I was afraid so. I believe it happens here: https://github.com/digitalbitbox/bitbox-wallet-app/blob/1bdf6d4/scripts/docker_install.sh#L58

```
/opt/android-sdk/tools/bin/sdkmanager "ndk-bundle" "platforms;android-29" "build-tools;29.0.0" "platform-tools"
```

SDK manager has probably installed NDK v22 in the new container image.  I bet if you try `sdkmanager --list` in the previous image, it'll show NDK v21.

I think we need to pin ndk-bundle in the line above until the upstream Go issue is resolved. So, I imagine the line would look something like this:

```
/opt/android-sdk/tools/bin/sdkmanager "ndk-bundle;21" "platforms;android-29" "build-tools;29.0.0" "platform-tools"
```

**Comment by x1ddos** [comment]
> need to pin ndk-bundle in the line above until the upstream Go issue is resolved

Actually, I'd prefer to always specify a version instead of relying on the "most recent".

**Comment by benma** [comment]
> > Now running into this for Android: [golang/go#42655](https://github.com/golang/go/issues/42655), same as in #1139 .. strange, since the android sdk and golang version didn't change in the Dockerfile
> 
> Yeah, I was afraid so. I believe it happens here: https://github.com/digitalbitbox/bitbox-wallet-app/blob/1bdf6d4/scripts/docker_install.sh#L58
> 
> ```
> /opt/android-sdk/tools/bin/sdkmanager "ndk-bundle" "platforms;android-29" "build-tools;29.0.0" "platform-tools"
> ```
> 
> SDK manager has probably installed NDK v22 in the new container image. I bet if you try `sdkmanager --list` in the previous image, it'll show NDK v21.
> 
> I think we need to pin ndk-bundle in the line above until the upstream Go issue is resolved. So, I imagine the line would look something like this:
> 
> ```
> /opt/android-sdk/tools/bin/sdkmanager "ndk-bundle;21" "platforms;android-29" "build-tools;29.0.0" "platform-tools"
> ```

I will compare and try your suggestion. I thought the ndk came from the fixed docker image:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/1bdf6d4b170e6de471352877c325ea68b188bc90/Dockerfile#L14

didn't see it was docker_install.sh :+1:

**Review by x1ddos — APPROVED** [review]
:tada: 

Thanks for fixing this! :pray:

**Comment by benma** [comment]
Travis really went to shit... still queued.

**Pull request merged**
