### PR TITLE
docker: upgrade nodejs to 14.x and go to 1.14.15

### PR DESCRIPTION
**Pull request by thisconnect**
Nodejs LTS 14.x is required by newer preact-cli.

While there, also upgrade Go. Been meaning to do it for a while. Seemed
like a good opportunity.

### CODE REVIEW

**Comment by thisconnect** [comment]
Rebased and upped go to 1.14.15, @x1ddos please rebuild docker and push 9

This supersedes https://github.com/digitalbitbox/bitbox-wallet-app/pull/1139

**Comment by x1ddos** [comment]
Built the new image. Versions look good:

```
root@1a094096d525:/opt/go/src/github.com/digitalbitbox/bitbox-wallet-app# node
node    nodejs
root@1a094096d525:/opt/go/src/github.com/digitalbitbox/bitbox-wallet-app# nodejs --version
v14.15.5
```

Both qt-linux and android build and run ok. Will push the new image to docker hub and ghcr.io.

**Comment by x1ddos** [comment]
Ok, New image should be ready for both CIs.

@thisconnect but please change the commit msg:

> This commit also switching from the now deprecated GitHub docker registry to its replacement ghcr.io

@benma did it in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1156

> On macOS, the yarn tool is now installed using npm

also done https://github.com/digitalbitbox/bitbox-wallet-app/pull/1156

**Comment by thisconnect** [comment]
Updated PTAL

**Review by x1ddos — APPROVED** [review]
LGTM but the commit title still says "... and switch to ghcr.io"

"All checks have passed" :heavy_check_mark: :tada:

**Comment by thisconnect** [comment]
> but the commit title still says "... and switch to ghcr.io"

🙈  aaaaaarrrgh :) fixed and merged, thanks

**Pull request merged**
