### PR TITLE
frontend/web: makes sidebar visible on lower screen resolution

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by thisconnect** [comment]
this is not fully tested yet.

**Comment by x1ddos** [comment]
@Stadicus maybe you can try this on your mac?

**Comment by Stadicus** [comment]
Tested with full compilation, works perfectly. Just the Account page is a bit too wide with a scrollbar at the bottom

**Comment by thisconnect** [comment]
Ready for testing

**Comment by Stadicus** [comment]
tACK https://github.com/digitalbitbox/bitbox-wallet-app/pull/813/commits/3873cdba34206b14d20782f6b3b8bc086bbc0be2

No more sidescrolling, looks very nice!

**Pull request merged**
