### PR TITLE
Frontend accountinfo guide

### PR DESCRIPTION
**Pull request by thisconnect**
on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1329

### CODE REVIEW

**Comment by benma** [comment]
@thisconnect btw the link/button to cycle the xpubs has the same issue as discussed recently in another PR: it looks like a link, but the mouse is not a hand. Other buttons that look like links do have a hand pointer, e.g. all the blue buttons in the app settings (Enable tor proxy, etc).

**Comment by thisconnect** [comment]
> Other buttons that look like links do have a hand pointer, e.g. all the blue buttons in the app settings (Enable tor proxy, etc).

yeah looks are inconsistent, one important style is focus for keyboard navigation. I'll add mouse pointer for now, but in the future want to remove them all unless they are links that open a browser.

**Comment by benma** [comment]
Please also update the CHANGELOG with an entry describing the change and that the keypaths are now shown

**Comment by thisconnect** [comment]
Updated changelog, mousepointer and cherry-picked guide into 
https://github.com/digitalbitbox/bitbox-wallet-app/pull/1329 

closing this.

**Pull request closed without merging**
