### PR TITLE
French

### PR DESCRIPTION
**Pull request by benma**

### CODE REVIEW

**Comment by x1ddos** [comment]
Travis is acting up again, it seems. Let me submit https://github.com/digitalbitbox/bitbox-wallet-app/pull/848.

**Comment by benma** [comment]
> Travis is acting up again, it seems. Let me submit #848.

It passed, just the notification didn't work:
https://travis-ci.org/github/digitalbitbox/bitbox-wallet-app/builds/697256031

**Comment by x1ddos** [comment]
> > Travis is acting up again, it seems. Let me submit #848.
> 
> It passed, just the notification didn't work:
> https://travis-ci.org/github/digitalbitbox/bitbox-wallet-app/builds/697256031

Yes, that's what I meant.

**Comment by x1ddos** [comment]
@benma could you rebase onto latest master? github CI runners should pick it up then.

**Comment by x1ddos** [comment]
> @benma could you rebase onto latest master? github CI runners should pick it up then.

Actually, no need. We already know CI passed.

**Pull request merged**
