### PR TITLE
Update Go CI Lint

### PR DESCRIPTION
**Pull request by maxmousee**
I'm trying to generate a native build using Apple Silicon and the first roadblock I hit was this library, for some reason and updating it seems to make the process go further.
I hope this helps :)

### CODE REVIEW

**Comment by benma** [comment]
We also need to build and update a new Docker image and running the CI with the new image.

**Comment by benma** [comment]
I pushed an updated Docker image. Could you please change this to tag `:13` instead of `:12`?

https://github.com/digitalbitbox/bitbox-wallet-app/blob/b25823611a3d6b0dce0d3dde46678fac7a304abf/scripts/travis-ci.sh#L17

**Comment by maxmousee** [comment]
> I pushed an updated Docker image. Could you please change this to tag `:13` instead of `:12`?
> 
> https://github.com/digitalbitbox/bitbox-wallet-app/blob/b25823611a3d6b0dce0d3dde46678fac7a304abf/scripts/travis-ci.sh#L17

Sure :)
Thank you very much

**Review by benma — APPROVED** [review]
thanks!

**Pull request merged**
