### PR TITLE
ci: update golangci to 1.55.2

### PR DESCRIPTION
**Pull request by benma**
Disable some useless/annoying linters.

### CODE REVIEW

**Comment by benma** [comment]
This needs a new docker image as golangci is pre-installed there

**Comment by Beerosagos** [comment]
It works locally, but trying to build a new docker image I got this error:
```
# Keep golangci-lint version in sync with what's in .github/workflows/ci.yml.
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b /opt/go/bin v1.55.2
golangci/golangci-lint info checking GitHub for tag 'v1.55.2'
golangci/golangci-lint info found version: 1.55.2 for v1.55.2/linux/amd64
golangci/golangci-lint info installed /opt/go/bin/golangci-lint
go install github.com/vektra/mockery/v2@latest
go: downloading github.com/vektra/mockery/v2 v2.39.1
go: downloading github.com/vektra/mockery v1.1.2
go: github.com/vektra/mockery/v2@latest (in github.com/vektra/mockery/v2@v2.39.1): go.mod:5: unknown directive: toolchain
make: Leaving directory '/tmp'
make: *** [Makefile:25: envinit] Error 1
Error: error building at STEP "RUN make -C /tmp/ envinit": error while running runtime: exit status 2
make: *** [Makefile:89: dockerinit] Errore 125
```

Following this issue, looks like it should be fixed now, but I'm not sure which package version should be bumped to have the fix. Is it golang? https://github.com/jeremylong/DependencyCheck/issues/6258

**Comment by benma** [comment]
@Beerosagos yeah they made 1.21 the minimum supported version :/ https://github.com/vektra/mockery/commit/b2484925496a4146c484637882120b9aa70ca90d

**Comment by benma** [comment]
@Beerosagos added a commit to update Go, PTAL

**Review by Beerosagos — APPROVED** [review]
tACK!

**Pull request merged**
